from __future__ import annotations

INDEX_HTML = """<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ServiceFlow 智能售后</title><style>
body{font-family:system-ui,"Microsoft YaHei",sans-serif;background:#f3f6fa;color:#172033;margin:0}.wrap{max-width:1050px;margin:30px auto;padding:0 20px}.hero{background:linear-gradient(120deg,#0f3d5e,#0e7490);color:white;padding:28px;border-radius:18px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px;margin-top:18px}.card{background:white;padding:20px;border-radius:14px;box-shadow:0 8px 30px #17324d12}label{display:block;font-size:13px;color:#526174;margin:9px 0 4px}input,select,textarea,button{box-sizing:border-box;width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}textarea{min-height:105px}button{background:#0e7490;color:#fff;border:0;font-weight:700;margin-top:12px;cursor:pointer}.reply{margin-top:14px;padding:14px;background:#f8fafc;border-left:4px solid #0e7490;white-space:pre-wrap}.danger{border-left-color:#dc2626}.meta{font-size:13px;color:#526174}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#cffafe;color:#155e75;margin:3px}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><section class="hero"><h1>ServiceFlow</h1><p>有证据、会转接、动作可确认、失败可恢复的智能售后工单 Agent</p></section><div class="grid"><section class="card"><h2>售后会话</h2><div class="grid"><div><label>客户</label><select id="customer"><option>C-001</option><option>C-002</option><option>C-003</option><option>C-004</option></select></div><div><label>订单</label><select id="order"><option>O-1001</option><option>O-1002</option><option>O-1003</option><option>O-1004</option></select></div></div><label>问题</label><textarea id="message">耳机蓝牙连不上怎么办？</textarea><button id="send">发送</button><div id="result"></div></section><aside class="card"><h2>受控能力</h2><p><span class="pill">知识引用</span><span class="pill">安全转人工</span></p><p><span class="pill">订单归属</span><span class="pill">确认令牌</span></p><p><span class="pill">事件日志</span><span class="pill">幂等退款</span></p><p id="health">正在检查服务…</p></aside></div></main><script>
let pending=null;fetch('/health').then(r=>r.json()).then(x=>health.textContent=`服务正常 · ${x.router} 路由 · ${x.tools} 个工具`);
send.onclick=async()=>{const request_id='web-'+Date.now();result.innerHTML='<p>处理中…</p>';const r=await fetch('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id,customer_id:customer.value,order_id:order.value,message:message.value})});const x=await r.json();pending=x.confirmation_token;result.innerHTML=`<div class="reply ${x.route==='safety'?'danger':''}">${x.message}</div><p class="meta">route=${x.route} · status=${x.status}${x.ticket_id?' · '+x.ticket_id:''}</p>`+(pending?'<button id="confirm">确认退款</button>':'');if(pending)confirm.onclick=confirmRefund};
async function confirmRefund(){const r=await fetch('/refund/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:pending,customer_id:customer.value})});const x=await r.json();result.innerHTML+=`<div class="reply">${x.message}</div><p class="meta">${JSON.stringify(x.diagnostics)}</p>`}
</script></body></html>"""

